#ifndef GUARD_CONSTANTS_QUEST_MENU_H
#define GUARD_CONSTANTS_QUEST_MENU_H

// Quest IDs for defeating each Gym Leader
#define QUEST_DEFEAT_ROXANNE       0
#define QUEST_DEFEAT_BRAWLY        1
#define QUEST_DEFEAT_WATTSON       2
#define QUEST_DEFEAT_FLANNERY      3
#define QUEST_DEFEAT_NORMAN        4
#define QUEST_DEFEAT_WINONA        5
#define QUEST_DEFEAT_TATE_AND_LIZA 6
#define QUEST_DEFEAT_JUAN          7

#define GYM_LEADER_QUEST_COUNT     8

// Rewards for completing each Gym Leader quest
#define QUEST_REWARD_ROXANNE       ITEM_MEGA_RING
#define QUEST_REWARD_BRAWLY        ITEM_TERA_ORB
#define QUEST_REWARD_WATTSON       ITEM_Z_POWER_RING
#define QUEST_REWARD_FLANNERY      ITEM_DYNAMAX_BAND
#define QUEST_REWARD_NORMAN        SPECIES_OGERPON
#define QUEST_REWARD_WINONA        SPECIES_OKIDOGI
#define QUEST_REWARD_TATE_AND_LIZA SPECIES_MUNKIDORI
#define QUEST_REWARD_JUAN          SPECIES_FEZANDIPITI

// Rewards for defeating each member of the Elite Four and Champion
#define QUEST_REWARD_SIDNEY        ITEM_OLD_SEA_MAP
#define QUEST_REWARD_PHOEBE        ITEM_AURORA_TICKET
#define QUEST_REWARD_GLACIA        ITEM_MYSTIC_TICKET
#define QUEST_REWARD_DRAKE         ITEM_EON_TICKET

// Rewards for capturing legendary Pokémon
#define QUEST_REWARD_REGIROCK      ITEM_HARD_STONE
#define QUEST_REWARD_REGICE        ITEM_NEVER_MELT_ICE
#define QUEST_REWARD_REGISTEEL     ITEM_METAL_COAT
#define QUEST_REWARD_GROUDON       ITEM_RED_ORB
#define QUEST_REWARD_KYOGRE        ITEM_BLUE_ORB
#define QUEST_REWARD_RAYQUAZA      ITEM_SKY_PLATE
#define QUEST_REWARD_LATIOS        ITEM_SOUL_DEW
#define QUEST_REWARD_LATIAS        ITEM_SOUL_DEW
#define QUEST_REWARD_JIRACHI       ITEM_STAR_PIECE
#define QUEST_REWARD_DEOXYS        ITEM_METEORITE
#define QUEST_REWARD_MEW           ITEM_MEWNIUM_Z
#define QUEST_REWARD_HOOPA         ITEM_PRISON_BOTTLE

#endif // GUARD_CONSTANTS_QUEST_MENU_H
