gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "The world... it's changing.\p"
	.string "Rifts are tearing it apart.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Legends sleep across every region.\p"
	.string "Some watch over us.\p"
	.string "Others... wait in the dark.\p"
	.string "But now, something is very wrong.\p"
	.string "The world is tearing open.\p"
	.string "POKéMON and people...\p"
	.string "appearing from nowhere.\p"
	.string "You...\p"
	.string "You have to help me\n"
	.string "figure this out.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "...{PLAYER}{KUN}?\p"
	.string "Is that really you...?\p"
	.string "It's been eleven years!\p"
	.string "You left Hoenn as a kid...\p"
	.string "And now you're back...\p"
	.string "just like this.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Listen...\p"
	.string "I don't have time to explain.\p"
	.string "Outside-\p"
	.string "Hoenn is falling apart!\p"
	.string "Something terrible is happening!\p"
	.string "Come find me-quickly!!\p"
	.string "$"

gText_PlayerOpt1_Yeah::
	.string "Yeah... it's been years.$"

gText_PlayerOpt1_Not::
	.string "Not by choice.$"

gText_PlayerOpt2_Yes::
	.string "What's inside?$"

gText_PlayerOpt2_No::
	.string "Later.$"
