LittlerootTown_Text_Selene_Opening1:
	.string "SELENE: You’ve already\n"
	.string "been through so much…\p"
	.string "You saved BIRCH and\n"
	.string "faced that strange\l"
	.string "POKéMON.$"
LittlerootTown_Text_Selene_Opening2:
	.string "SELENE: I’m proud of you.\n"
	.string "But as your mother…\p"
	.string "I still worry. The\n"
	.string "world feels unsettled\l"
	.string "lately.$"
LittlerootTown_Text_Selene_GiveShoes:
	.string "SELENE: Here—RUNNING\n"
	.string "SHOES for you!\p"
	.string "They’ll help you move\n"
	.string "quickly on your path.$"
LittlerootTown_Text_Player_ThanksForShoes:
	.string "{COLOR GREEN}{PLAYER}: Thank you,\n"
	.string "Mother.\p"
	.string "I’ll use them well.{COLOR DARK_GRAY}$"
LittlerootTown_Text_Selene_GiveBand1:
	.string "SELENE: And this…\p"
	.string "Caelum wanted you\n"
	.string "to have it.$"
LittlerootTown_Text_Selene_GiveBand2:
	.string "SELENE: He said this\n"
	.string "band means trust—\p"
	.string "not just strength.\n"
	.string "Be ready for what’s next.$"
LittlerootTown_Text_ReceivedDynamaxBand:
	.string "{PLAYER} got the\n"
	.string "DYNAMAX BAND!$"
LittlerootTown_Text_Player_FatherAside1:
	.string "{COLOR GREEN}{PLAYER}: (Father…\n"
	.string "is this what you\l"
	.string "left for me?){COLOR DARK_GRAY}$"
LittlerootTown_Text_Player_FatherAside2:
	.string "{COLOR GREEN}{PLAYER}: I’ll carry\n"
	.string "it carefully.\p"
	.string "I promise.{COLOR DARK_GRAY}$"
LittlerootTown_Text_Selene_HeartSteady:
	.string "SELENE: That’s all I\n"
	.string "could ask.\p"
	.string "Keep your heart steady,\n"
	.string "{PLAYER}.\p"
	.string "No matter how strange\n"
	.string "things get, you’re\l"
	.string "not alone.$"
LittlerootTown_Text_Selene_HeIsWaiting:
	.string "SELENE: He is waiting.$"
LittlerootTown_Text_Player_HeWho:
	.string "{COLOR GREEN}{PLAYER}: …He?\n"
	.string "Who…?{COLOR DARK_GRAY}$"
LittlerootTown_Text_Player_MaybeBirch:
	.string "{COLOR GREEN}{PLAYER}: (Maybe she\n"
	.string "means BIRCH.\p"
	.string "I shouldn’t keep him\n"
	.string "waiting.){COLOR DARK_GRAY}$"
LittlerootTown_Text_Selene_JourneyBegins:
	.string "SELENE: Go on now.\n"
	.string "Your journey begins!$"
